//! P5 Task 5: revision geometry (D6), the D5 transform vectors, and the D7
//! plate writer, over the committed fixtures.
//!
//! - Every STL and 3MF fixture under `tests/fixtures/library/` loads as
//!   geometry whose counts agree with its P4 inspection, and every fixture
//!   P4 rejects is rejected here with the same code.
//! - `tests/fixtures/slicing/transform-vectors.json` holds the D5 golden
//!   vectors shared with the frontend.
//! - The D23 deterministic invocation fixtures:
//!   `tests/fixtures/slicing/two-cube-plate.3mf` (the D7 plate bytes),
//!   `argument-vectors.json` (D8's arguments with `<engine>` and `<work>`
//!   placeholders, with and without Linux's `--pipe`), and
//!   `flat-presets.json` (the TestVendor fixture's default machine,
//!   process, and filament presets, flattened as a slice writes them).
//! - All of them are regenerated by `regenerate_slicing_fixtures` through
//!   `just gen-slicing-fixtures`, and the tests compare fresh output with
//!   the committed files.
//! - `real_orca_places_a_written_plate_exactly` is `#[ignore]` and needs a
//!   real OrcaSlicer in `FARM3D_ORCA` (spec D23, spike Gate C).

use std::fs::{self, File};
use std::path::{Path, PathBuf};

use farm3d_lib::library::content::CancelFlag;
use farm3d_lib::library::formats::{self, BoundsMm, Inspection};
use farm3d_lib::library::ModelFormat;
use farm3d_lib::slicing::geometry::{
    compose_transform, load_revision, transform_point, transformed_bounds, LoadedRevision,
    MESH_FORMAT_VERSION, MESH_MAGIC,
};
use farm3d_lib::slicing::invocation::{recorded_arguments, WorkDir};
use farm3d_lib::slicing::plate3mf::write_plate_3mf;
use farm3d_lib::slicing::presets::{default_filament, default_process, PresetIndex, PresetKind};
use farm3d_lib::slicing::{InstanceDoc, InstanceTransform, PlateDoc};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

fn library_fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/library")
}

fn slicing_fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/slicing")
}

const VECTORS: &str = "transform-vectors.json";
const PLATE: &str = "two-cube-plate.3mf";
const ARGUMENTS: &str = "argument-vectors.json";
const FLAT_PRESETS: &str = "flat-presets.json";
const PLATE_SOURCE: &str = "cube-for-slicers.stl";

fn load(path: &Path, format: ModelFormat) -> Result<LoadedRevision, formats::InspectError> {
    load_revision(File::open(path).unwrap(), format, &CancelFlag::never())
}

fn header_word(buffer: &[u8], at: usize) -> u32 {
    u32::from_le_bytes(buffer[at..at + 4].try_into().unwrap())
}

fn assert_bounds_near(actual: &BoundsMm, expected: &BoundsMm, tolerance: f64, what: &str) {
    for axis in 0..3 {
        assert!(
            (actual.min[axis] - expected.min[axis]).abs() <= tolerance
                && (actual.max[axis] - expected.max[axis]).abs() <= tolerance,
            "{what}: {actual:?} != {expected:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// Geometry for every model fixture
// ---------------------------------------------------------------------------

#[test]
fn every_model_fixture_has_geometry_and_a_mesh_buffer_or_is_rejected_as_before() {
    let dir = library_fixtures();
    let mut names: Vec<String> = fs::read_dir(&dir)
        .unwrap()
        .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".stl") || name.ends_with(".3mf"))
        .collect();
    names.sort();
    assert!(names.len() >= 14, "{names:?}");

    let mut loaded = Vec::new();
    for name in &names {
        let path = dir.join(name);
        let oracle: serde_json::Value =
            serde_json::from_slice(&fs::read(dir.join(format!("{name}.expected.json"))).unwrap())
                .unwrap();
        let detected = formats::detect(&path);
        if let Some(code) = oracle.get("error").and_then(|code| code.as_str()) {
            let error = match detected {
                Err(error) => error,
                Ok(detected) => {
                    load(&path, detected.format).expect_err(&format!("{name} should be rejected"))
                }
            };
            assert_eq!(error.code(), code, "{name}: {error:?}");
            continue;
        }

        let detected = detected.unwrap();
        let inspection = formats::inspect(&path, &detected, &CancelFlag::never())
            .unwrap()
            .inspection;
        let revision =
            load(&path, detected.format).unwrap_or_else(|error| panic!("{name}: {error:?}"));
        let geometry = revision.geometry();

        // Every object's buffer decodes to its mesh's counts.
        for object in &geometry.objects {
            let mesh = revision.mesh(object.object_key).unwrap();
            let buffer = revision.mesh_buffer(object.object_key).unwrap();
            assert_eq!(buffer[..4], MESH_MAGIC, "{name}");
            assert_eq!(header_word(&buffer, 4), MESH_FORMAT_VERSION, "{name}");
            assert_eq!(header_word(&buffer, 8) as usize, mesh.positions.len());
            assert_eq!(header_word(&buffer, 12) as usize, mesh.triangles.len() * 3);
            assert_eq!(
                buffer.len(),
                16 + mesh.positions.len() * 12 + mesh.triangles.len() * 12,
                "{name}"
            );
            assert_eq!(object.triangle_count as usize, mesh.triangles.len());
            assert!(!object.lay_flat_faces.is_empty(), "{name}");
            assert!(object.lay_flat_faces.len() <= 8, "{name}");
        }

        // The triangles as placed match P4's count, and the placed bounds
        // match P4's corner-method bounds (every fixture is axis-aligned).
        let mut placed_triangles = 0;
        let mut placed_bounds: Option<BoundsMm> = None;
        for item in &geometry.build_items {
            let object = geometry
                .objects
                .iter()
                .find(|object| object.object_key == item.object_key)
                .unwrap();
            placed_triangles += object.triangle_count;
            let mesh = revision.mesh(item.object_key).unwrap();
            let bounds = transformed_bounds(&item.transform, &mesh.positions).unwrap();
            placed_bounds = Some(match placed_bounds {
                None => bounds,
                Some(mut union) => {
                    for axis in 0..3 {
                        union.min[axis] = union.min[axis].min(bounds.min[axis]);
                        union.max[axis] = union.max[axis].max(bounds.max[axis]);
                    }
                    union
                }
            });
        }
        let (triangles, bounds) = match &inspection {
            Inspection::Stl(stl) => (stl.triangle_count, stl.bounds_mm),
            Inspection::ThreeMf(model) => {
                assert_eq!(geometry.build_items.len(), model.build_item_count as usize);
                assert!(geometry.objects.len() <= model.object_count as usize);
                (model.triangle_count, model.bounds_mm)
            }
            Inspection::Gcode(_) => unreachable!("only STL and 3MF are listed"),
        };
        assert_eq!(placed_triangles, triangles, "{name}");
        assert_bounds_near(&placed_bounds.unwrap(), &bounds, 1e-4, name);
        loaded.push((name.clone(), revision));
    }

    let loaded_names: Vec<&str> = loaded.iter().map(|(name, _)| name.as_str()).collect();
    assert_eq!(
        loaded_names,
        [
            "core-two-objects.3mf",
            "cube-ascii-bare-solid.stl",
            "cube-ascii.stl",
            "cube-binary-solid-header.stl",
            "cube-binary.stl",
            "cube-for-slicers.stl",
            "orca-two-plates.3mf",
            "prusa-project.3mf",
        ]
    );
    for (name, revision) in &loaded {
        let geometry = revision.geometry();
        let summary: Vec<(u32, Option<&str>, usize, u64)> = geometry
            .objects
            .iter()
            .map(|object| {
                (
                    object.object_key,
                    object.name.as_deref(),
                    revision.mesh(object.object_key).unwrap().positions.len(),
                    object.triangle_count,
                )
            })
            .collect();
        let items: Vec<(u32, Option<u32>, bool)> = geometry
            .build_items
            .iter()
            .map(|item| (item.object_key, item.plate_index, item.printable))
            .collect();
        match name.as_str() {
            // Welded STL cubes: 8 vertices, 12 triangles, one object.
            stl if stl.ends_with(".stl") => {
                assert_eq!(summary, [(1, None, 8, 12)], "{name}");
                assert_eq!(items, [(1, None, true)], "{name}");
                let faces = &geometry.objects[0].lay_flat_faces;
                assert_eq!(faces.len(), 6, "{name}");
                assert!(faces
                    .iter()
                    .all(|face| (face.area_mm2 - 100.0).abs() < 1e-9));
            }
            "core-two-objects.3mf" => {
                assert_eq!(
                    summary,
                    [(1, Some("Cube A"), 8, 12), (2, Some("Cube B"), 8, 12)]
                );
                assert_eq!(items, [(1, None, true), (2, None, true)]);
                // Object 2's component is flattened into its frame.
                assert_eq!(geometry.objects[1].bounds_mm.min, [20.0, 0.0, 0.0]);
            }
            "orca-two-plates.3mf" => {
                assert_eq!(
                    summary,
                    [
                        (2, Some("cube-for-slicers.stl"), 8, 12),
                        (4, Some("cube-for-slicers.stl"), 8, 12)
                    ]
                );
                assert_eq!(items, [(2, Some(1), true), (4, Some(2), true)]);
                assert_eq!(geometry.build_items[1].transform[9..], [425.0, 119.0, 5.0]);
            }
            "prusa-project.3mf" => {
                assert_eq!(summary, [(1, None, 8, 12)]);
                assert_eq!(items, [(1, None, true)]);
            }
            other => panic!("unexpected fixture {other}"),
        }
    }
}

// ---------------------------------------------------------------------------
// D5 transform vectors
// ---------------------------------------------------------------------------

/// `transform-vectors.json`: shared with the frontend's D5 implementation.
#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
struct TransformVectors {
    description: String,
    tolerance: f64,
    positions: Vec<[f32; 3]>,
    cases: Vec<TransformCase>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
struct TransformCase {
    name: String,
    transform: InstanceTransform,
    matrix: [f64; 12],
    world_bounds_mm: BoundsMm,
}

fn vector_inputs() -> (Vec<[f32; 3]>, Vec<(&'static str, InstanceTransform)>) {
    // A lopsided octahedron: its bounding-box corners aren't vertices, so a
    // box-based Z drop would differ from the vertex-based one.
    let positions = vec![
        [10.0, 0.0, 5.0],
        [-10.0, 0.0, 5.0],
        [0.0, 6.0, 5.0],
        [0.0, -6.0, 5.0],
        [0.0, 0.0, 15.0],
        [0.0, 0.0, -3.0],
        [4.0, 2.0, 9.0],
    ];
    let case = |translate: [f64; 2], rotate: [f64; 3], scale: [f64; 3]| InstanceTransform {
        translate_mm: translate,
        rotate_deg: rotate,
        scale,
    };
    let cases = vec![
        ("identity", case([0.0; 2], [0.0; 3], [1.0; 3])),
        ("rotateX90", case([0.0; 2], [90.0, 0.0, 0.0], [1.0; 3])),
        ("rotateY90", case([0.0; 2], [0.0, 90.0, 0.0], [1.0; 3])),
        ("rotateZ90", case([0.0; 2], [0.0, 0.0, 90.0], [1.0; 3])),
        ("rotateX30", case([0.0; 2], [30.0, 0.0, 0.0], [1.0; 3])),
        ("nonUniformScale", case([0.0; 2], [0.0; 3], [2.0, 0.5, 3.0])),
        (
            "combined",
            case([100.0, 50.0], [30.0, 45.0, 60.0], [1.5, 1.0, 0.75]),
        ),
        (
            "rotateZ45Translated",
            case([150.0, 120.0], [0.0, 0.0, 45.0], [1.0; 3]),
        ),
    ];
    (positions, cases)
}

fn computed_vectors() -> TransformVectors {
    let (positions, cases) = vector_inputs();
    let cases = cases
        .into_iter()
        .map(|(name, transform)| {
            let matrix = compose_transform(&transform, &positions);
            TransformCase {
                name: name.to_string(),
                world_bounds_mm: transformed_bounds(&matrix, &positions).unwrap(),
                transform,
                matrix,
            }
        })
        .collect();
    TransformVectors {
        description: "D5 instance transforms. The local mesh is scaled, rotated about X, then \
            Y, then Z (extrinsic, rad = deg * (PI / 180)), and translated by translateMm on \
            XY. matrix is the 3MF transform attribute order m00 m01 m02 m10 m11 m12 m20 m21 \
            m22 m30 m31 m32: a local point maps to x' = x*m[0] + y*m[3] + z*m[6] + m[9], \
            y' = x*m[1] + y*m[4] + z*m[7] + m[10], z' = x*m[2] + y*m[5] + z*m[8] + m[11]. \
            m[11] = -min over the vertices of ((x*m[2] + y*m[5]) + z*m[8]), so the lowest \
            vertex lands exactly on Z = 0. worldBoundsMm is over the placed vertices. \
            Compare numbers within tolerance."
            .to_string(),
        tolerance: 1e-9,
        positions,
        cases,
    }
}

#[test]
fn transform_vectors_match_the_d5_composition() {
    let text = fs::read_to_string(slicing_fixtures().join(VECTORS)).unwrap();
    let committed: TransformVectors = serde_json::from_str(&text).unwrap();
    let computed = computed_vectors();
    assert_eq!(committed.positions, computed.positions);
    assert_eq!(committed.cases.len(), computed.cases.len());
    let tolerance = committed.tolerance;
    assert_eq!(tolerance, 1e-9);
    for (committed, computed) in committed.cases.iter().zip(&computed.cases) {
        assert_eq!(committed.name, computed.name);
        assert_eq!(
            committed.transform, computed.transform,
            "{}",
            committed.name
        );
        for (index, (a, b)) in committed.matrix.iter().zip(&computed.matrix).enumerate() {
            assert!(
                (a - b).abs() <= tolerance,
                "{} m[{index}]: {a} != {b}",
                committed.name
            );
        }
        assert_bounds_near(
            &committed.world_bounds_mm,
            &computed.world_bounds_mm,
            tolerance,
            &committed.name,
        );
        assert_eq!(computed.world_bounds_mm.min[2], 0.0, "{}", committed.name);
        assert!(
            (committed.transform.translate_mm[0] - committed.matrix[9]).abs() <= tolerance
                && (committed.transform.translate_mm[1] - committed.matrix[10]).abs() <= tolerance
        );
    }

    // Spot checks independent of the implementation.
    let by_name = |name: &str| {
        computed
            .cases
            .iter()
            .find(|case| case.name == name)
            .unwrap()
    };
    // Identity: the apex at z = -3 drops the mesh by 3.
    assert_bounds_near(
        &by_name("identity").world_bounds_mm,
        &BoundsMm {
            min: [-10.0, -6.0, 0.0],
            max: [10.0, 6.0, 18.0],
        },
        1e-9,
        "identity",
    );
    // About X by 90°: y' = -z and z' = y, so z spans -6..6, dropped by 6.
    assert_bounds_near(
        &by_name("rotateX90").world_bounds_mm,
        &BoundsMm {
            min: [-10.0, -15.0, 0.0],
            max: [10.0, 3.0, 12.0],
        },
        1e-9,
        "rotateX90",
    );
    // Non-uniform scale: z × 3 spans -9..45.
    assert_bounds_near(
        &by_name("nonUniformScale").world_bounds_mm,
        &BoundsMm {
            min: [-20.0, -3.0, 0.0],
            max: [20.0, 3.0, 54.0],
        },
        1e-9,
        "nonUniformScale",
    );
    let placed = transform_point(&by_name("rotateZ45Translated").matrix, [10.0, 0.0, 0.0]);
    let half = 10.0 * std::f64::consts::FRAC_1_SQRT_2;
    assert!((placed[0] - (150.0 + half)).abs() < 1e-9 && (placed[1] - (120.0 + half)).abs() < 1e-9);
}

// ---------------------------------------------------------------------------
// D7 plate writer
// ---------------------------------------------------------------------------

fn instance(key: &str, translate: [f64; 2], rotate_z: f64, scale: f64) -> InstanceDoc {
    InstanceDoc {
        instance_key: key.to_string(),
        object_key: 1,
        transform: InstanceTransform {
            translate_mm: translate,
            rotate_deg: [0.0, 0.0, rotate_z],
            scale: [scale; 3],
        },
    }
}

/// Gate C's layout: cube A at (40, 40), cube B at (150, 120) turned 45°.
fn two_cube_plate(scale: f64) -> PlateDoc {
    PlateDoc {
        plate_key: "plate-1".to_string(),
        name: Some("Two cubes".to_string()),
        instances: vec![
            instance("instance-a", [40.0, 40.0], 0.0, scale),
            instance("instance-b", [150.0, 120.0], 45.0, scale),
        ],
    }
}

fn plate_source() -> LoadedRevision {
    load(&library_fixtures().join(PLATE_SOURCE), ModelFormat::Stl).unwrap()
}

// ---------------------------------------------------------------------------
// D23 deterministic invocation fixtures
// ---------------------------------------------------------------------------

/// D8's argument vectors as the manifest records them, for a work
/// directory at an arbitrary path: with `--pipe` (Linux) and without.
fn argument_vectors() -> Value {
    let work = WorkDir::at(PathBuf::from("/any/content/slicing-work/sop-fixture"));
    json!({
        "linux": recorded_arguments(&work, true),
        "otherPlatforms": recorded_arguments(&work, false),
    })
}

/// The TestVendor fixture's default machine, process, and filament presets
/// for its Test Printer (D3's defaults, no Spool loaded), flattened.
fn flat_presets() -> Value {
    let profiles = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/profiles");
    let index = PresetIndex::build(&profiles, "2.4.2", &CancelFlag::never()).unwrap();
    let machine = "Test Printer 0.4 nozzle";
    let process = default_process(&index.offered(PresetKind::Process, machine)).unwrap();
    let filament = default_filament(&index.offered(PresetKind::Filament, machine), &[]).unwrap();
    let flat = |kind, name: &str| Value::Object(index.flatten(kind, name).unwrap());
    json!({
        "machine": flat(PresetKind::Machine, machine),
        "process": flat(PresetKind::Process, &process),
        "filament": flat(PresetKind::Filament, &filament),
    })
}

fn pretty(value: &Value) -> Vec<u8> {
    (serde_json::to_string_pretty(value).unwrap() + "\n").into_bytes()
}

/// Every deterministic invocation fixture, by file name, as this build
/// produces it.
fn invocation_fixtures() -> [(&'static str, Vec<u8>); 3] {
    [
        (
            PLATE,
            write_plate_3mf(&two_cube_plate(1.0), &plate_source()).unwrap(),
        ),
        (ARGUMENTS, pretty(&argument_vectors())),
        (FLAT_PRESETS, pretty(&flat_presets())),
    ]
}

#[test]
fn the_deterministic_invocation_fixtures_match_the_committed_ones() {
    for (name, produced) in invocation_fixtures() {
        let committed = fs::read(slicing_fixtures().join(name))
            .unwrap_or_else(|error| panic!("{name}: {error}; run `just gen-slicing-fixtures`"));
        assert!(
            produced == committed,
            "{name} differs ({} bytes produced, {} committed); run `just gen-slicing-fixtures` \
             if the change is intended",
            produced.len(),
            committed.len()
        );
    }
}

#[test]
fn the_argument_vectors_carry_no_absolute_path_and_no_forbidden_flag() {
    for (platform, arguments) in argument_vectors().as_object().unwrap() {
        let arguments: Vec<&str> = arguments
            .as_array()
            .unwrap()
            .iter()
            .map(|argument| argument.as_str().unwrap())
            .collect();
        assert_eq!(arguments[0], "<engine>", "{platform}");
        for argument in &arguments {
            assert!(
                !argument.starts_with('/') && !argument.contains("/any/"),
                "{platform}: {argument}"
            );
            for forbidden in ["--allow-newer-file", "--mstpp", "--no-check", "--debug"] {
                assert_ne!(*argument, forbidden, "{platform}");
            }
        }
        assert_eq!(
            arguments.contains(&"--pipe"),
            platform == "linux",
            "{platform}"
        );
    }
}

#[test]
fn the_flat_presets_are_system_presets_with_no_inherits() {
    let presets = flat_presets();
    for kind in ["machine", "process", "filament"] {
        let preset = &presets[kind];
        assert_eq!(preset["from"], "system", "{kind}");
        assert!(preset.get("inherits").is_none(), "{kind}");
        assert!(preset["name"].is_string(), "{kind}");
    }
}

#[test]
fn the_golden_plate_reads_back_through_the_p4_readers() {
    let path = slicing_fixtures().join(PLATE);
    let detected = formats::detect(&path).unwrap();
    assert_eq!(detected.format, ModelFormat::ThreeMf);
    let outcome = formats::inspect(&path, &detected, &CancelFlag::never()).unwrap();
    assert!(outcome.warnings.is_empty(), "{:?}", outcome.warnings);
    let Inspection::ThreeMf(model) = outcome.inspection else {
        panic!("not a 3MF");
    };
    assert_eq!(model.object_count, 1);
    assert_eq!(model.build_item_count, 2);
    assert_eq!(model.triangle_count, 24);
    assert!(model.plates.is_empty() && model.unsupported.is_empty());
    let half_diagonal = 10.0 * std::f64::consts::FRAC_1_SQRT_2;
    assert_bounds_near(
        &model.bounds_mm,
        &BoundsMm {
            min: [40.0, 40.0, 0.0],
            max: [150.0 + half_diagonal, 120.0 + 2.0 * half_diagonal, 10.0],
        },
        1e-5,
        PLATE,
    );

    // The items carry the composed transforms (to 6 decimal places).
    let source = plate_source();
    let read_back = load(&path, ModelFormat::ThreeMf).unwrap();
    let plate = two_cube_plate(1.0);
    for (item, instance) in read_back
        .geometry()
        .build_items
        .iter()
        .zip(&plate.instances)
    {
        let expected = compose_transform(&instance.transform, &source.mesh(1).unwrap().positions);
        for (a, b) in item.transform.iter().zip(&expected) {
            assert!(
                (a - b).abs() <= 5e-7,
                "{:?} != {expected:?}",
                item.transform
            );
        }
    }
    assert_eq!(read_back.mesh(1), source.mesh(1));
}

/// `just gen-slicing-fixtures`
#[test]
#[ignore = "writes fixtures; run through `just gen-slicing-fixtures`"]
fn regenerate_slicing_fixtures() {
    let dir = slicing_fixtures();
    fs::create_dir_all(&dir).unwrap();
    let vectors = serde_json::to_string_pretty(&computed_vectors()).unwrap() + "\n";
    fs::write(dir.join(VECTORS), vectors).unwrap();
    for (name, bytes) in invocation_fixtures() {
        fs::write(dir.join(name), bytes).unwrap();
    }
}

// ---------------------------------------------------------------------------
// Real OrcaSlicer (spec D23, spike Gate C)
// ---------------------------------------------------------------------------

/// The XY extents of extrusion moves on the layers between `z_low` and
/// `z_high`, split into objects left and right of `x_split`.
fn extrusion_extents(gcode: &str, z_low: f64, z_high: f64, x_split: f64) -> [BoundsMm; 2] {
    let mut z = 0.0;
    let mut position = [0.0f64; 2];
    let mut extents: [Option<BoundsMm>; 2] = [None, None];
    for line in gcode.lines() {
        let line = line.split(';').next().unwrap_or("").trim();
        let mut words = line.split_whitespace();
        if !matches!(words.next(), Some("G1" | "G0")) {
            continue;
        }
        let mut extrudes = false;
        for word in words {
            let (axis, value) = word.split_at(1);
            let Ok(value) = value.parse::<f64>() else {
                continue;
            };
            match axis {
                "X" => position[0] = value,
                "Y" => position[1] = value,
                "Z" => z = value,
                "E" => extrudes = value > 0.0,
                _ => {}
            }
        }
        if extrudes && (z_low..=z_high).contains(&z) {
            let side = usize::from(position[0] >= x_split);
            let point = [position[0], position[1], z];
            match &mut extents[side] {
                Some(bounds) => {
                    let ranges = bounds.min.iter_mut().zip(bounds.max.iter_mut());
                    for ((min, max), value) in ranges.zip(point) {
                        *min = min.min(value);
                        *max = max.max(value);
                    }
                }
                none => {
                    *none = Some(BoundsMm {
                        min: point,
                        max: point,
                    })
                }
            }
        }
    }
    extents.map(|bounds| bounds.expect("both objects are extruded on the checked layers"))
}

#[test]
#[ignore = "needs a real OrcaSlicer: set FARM3D_ORCA (just test-orca)"]
fn real_orca_places_a_written_plate_exactly() {
    use farm3d_lib::slicing::presets::{
        default_filament, default_process, PresetIndex, PresetKind,
    };
    use farm3d_lib::slicing::repository::SlicerRuntimeConfig;
    use farm3d_lib::slicing::runtime::{orca_environment, resolve_runtime, DiscoveryEnv};
    use farm3d_lib::spools::MaterialFamily;

    let engine = std::env::var_os("FARM3D_ORCA")
        .map(PathBuf::from)
        .expect("FARM3D_ORCA must name an OrcaSlicer engine; run through `just test-orca`");
    let presets = std::env::var_os("FARM3D_ORCA_PRESETS").map(PathBuf::from);
    let cache = tempfile::tempdir().unwrap();
    let runtime = resolve_runtime(
        &SlicerRuntimeConfig {
            revision: 1,
            engine_path: Some(engine.to_str().unwrap().to_string()),
            preset_source_path: presets.map(|path| path.to_str().unwrap().to_string()),
            updated_at: None,
        },
        &DiscoveryEnv {
            home: None,
            path_var: None,
            probe_timeout: std::time::Duration::from_secs(20),
        },
        cache.path(),
    );
    let engine = runtime.engine.expect("an accepted engine");
    let source = runtime.preset_source.expect("a readable preset source");
    let index = PresetIndex::build(
        &source.profiles_dir,
        &source.version.to_string(),
        &CancelFlag::never(),
    )
    .unwrap();
    let machine = "Elegoo Centauri Carbon 0.4 nozzle";
    let process = default_process(&index.offered(PresetKind::Process, machine)).unwrap();
    let filament = default_filament(
        &index.offered(PresetKind::Filament, machine),
        &[MaterialFamily::Pla],
    )
    .unwrap();

    let work = tempfile::tempdir().unwrap();
    let input = work.path().join("input");
    let out = work.path().join("out");
    let datadir = work.path().join("datadir");
    for dir in [&input, &out, &datadir] {
        fs::create_dir_all(dir).unwrap();
    }
    for (kind, name, file) in [
        (PresetKind::Machine, machine, "machine.json"),
        (PresetKind::Process, process.as_str(), "process.json"),
        (PresetKind::Filament, filament.as_str(), "filament.json"),
    ] {
        let flat = index.flatten(kind, name).unwrap();
        fs::write(input.join(file), serde_json::to_vec_pretty(&flat).unwrap()).unwrap();
    }
    // Gate C: 20 mm cubes.
    let plate = write_plate_3mf(&two_cube_plate(2.0), &plate_source()).unwrap();
    fs::write(input.join("plate.3mf"), plate).unwrap();

    let status = std::process::Command::new(&engine.path)
        .current_dir(work.path())
        .env_clear()
        .envs(orca_environment())
        .arg("--datadir")
        .arg(&datadir)
        .arg("--outputdir")
        .arg(&out)
        .arg("--load-settings")
        .arg(format!(
            "{};{}",
            input.join("machine.json").display(),
            input.join("process.json").display()
        ))
        .arg("--load-filaments")
        .arg(input.join("filament.json"))
        .args(["--arrange", "0", "--orient", "0", "--slice", "1"])
        .arg(input.join("plate.3mf"))
        .status()
        .unwrap();
    assert!(status.success(), "OrcaSlicer exited with {status}");
    let gcode = fs::read_to_string(out.join("plate_1.gcode")).unwrap();

    // Around mid-height (Z 10 of 20), perimeters sit about 0.21 mm inside
    // the footprint (Gate C).
    let [a, b] = extrusion_extents(&gcode, 9.5, 10.5, 100.0);
    eprintln!("A: {a:?}\nB: {b:?}");
    let diagonal = 20.0 * std::f64::consts::SQRT_2;
    let expected_a = BoundsMm {
        min: [40.0, 40.0, 0.0],
        max: [60.0, 60.0, 0.0],
    };
    let expected_b = BoundsMm {
        min: [150.0 - diagonal / 2.0, 120.0, 0.0],
        max: [150.0 + diagonal / 2.0, 120.0 + diagonal, 0.0],
    };
    for (actual, expected, what) in [(a, expected_a, "A"), (b, expected_b, "B")] {
        for axis in 0..2 {
            assert!(
                (actual.min[axis] - expected.min[axis]).abs() < 0.6
                    && (actual.max[axis] - expected.max[axis]).abs() < 0.6,
                "{what}: {actual:?} vs {expected:?}"
            );
        }
    }
}
